# Generated by Django 3.2.7 on 2021-10-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210930_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.CharField(blank=True, choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200, null=True),
        ),
    ]
