# Generated by Django 3.2.7 on 2021-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projects_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(blank=True, to='projects.Tag'),
        ),
    ]
